app:
  scheduler:
    enable: true
    interval: 10000
    initial-delay: 10000
    force-check-delay: 0
    check-limit: 10
  databaseAccessType: jpa

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5435/scrapper
    username: postgres
    password: postgres
  jooq:
    sql-dialect: postgres
  jpa:
    hibernate:
      ddl-auto: validate

api-client:
  github:
    base-url: https://api.github.com
    auth-token: ${GITHUB_AUTH_TOKEN:}
  stackoverflow:
    base-url: https://api.stackexchange.com/2.3
  bot:
    base-url: ${BOT_API_CLIENT_BASE_URL}

retry:
  bot:
    retry-type: linear
    max-retries: 3
    initial-interval: 10s
    codes: 500, 501, 502, 503, 504, 521, 522, 523, 524
  github:
    retry-type: linear
    max-retries: 3
    initial-interval: 10s
    codes: 500, 501, 502, 503, 504, 521, 522, 523, 524
  stackoverflow:
    retry-type: linear
    max-retries: 3
    initial-interval: 10s
    codes: 500, 501, 502, 503, 504, 521, 522, 523, 524

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
